apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/part-of: yield-control-plane
      app.kubernetes.io/managed-by: kustomize
      yield-control-plane.local/runtime: kind-localstack

